### ISSUE TITLE
Errors (cuz im picky)

### ISSUE THREAD

**Issue by AlanTheGreat2018** [ReFlar/flarum-docs#1]
Missing text after `appear next to the` [here](https://github.com/ReFlar/flarum-docs/compare/4fb50eb93a07...3193f1865db1#diff-88c4219acdd0c4f0a7bd6a6d71bcefd3R132)

Grammatical Error [here](https://github.com/ReFlar/flarum-docs/compare/4fb50eb93a07...3193f1865db1#diff-88c4219acdd0c4f0a7bd6a6d71bcefd3R132), should be `Or on our Discord channel`

**Comment by CDK2020** [comment]
Fixed in c6cb69213f8c062a8b24fab122ec3170298fc176
